services:
  api_gateway:
    container_name: whymsg-api-gateway
    build:
      context: ..
      dockerfile: api_gateway/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - PASSPORT_URL=http://whymsg-passport:8080
      - POSTS_URL=http://whymsg-posts:8080
  
networks:
  default:
    name: whymsg-network
    external: true
